INCLUDE_ASM = "INCLUDE_ASM"
INCLUDE_ASM_REGEX = rf'{INCLUDE_ASM}\("(.*)", (.*)\)'

INCLUDE_RODATA = "INCLUDE_RODATA"
INCLUDE_RODATA_REGEX = rf'{INCLUDE_RODATA}\("(.*)", (.*)\)'

DOLLAR_SIGN = "$"

FUNCTION_PREFIX = "mwccgap_"
SYMBOL_AT = "__at__"
SYMBOL_DOLLAR = "__dollar__"

LOCAL_SUFFIX = ", local"
