name: mypy

on:
  pull_request:
  push:

permissions: read-all

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m pip install --user mypy==1.10.0
      - run: python3 -m mypy .
